package gitprocessor

// Used to define Github Params that should be send to the github api when searching repositories
type gitQueryParams struct {
	Sort    string `url:"sort,omitempty"`
	Query   string `url:"q"`
	PerPage int    `url:"per_page,omitempty"`
}

// GitRepository is the api representation of a github repository
// This is a subpart of the json response generated by the search API
type GitRepository struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Language string `json:"language"`
	FullName string `json:"full_name"`
}

// gitQuery is the main structure used by the github search api.
// Not all field returned are present in this structure !
type gitQueryResponse struct {
	TotalCount int             `json:"total_count"`
	Items      []GitRepository `json:"items"`
}

// GitLanguages is a simple representation of the git language response json object
type GitLanguages map[string]int
